ahoyapi: v2
commands:
  build-gui:
    cmd: docker build -t ros:nvidia .
  ros:
    usage: Run the full ROS desktop container with gpu and GUI support
    cmd: | 
      nvidia-docker run -it --rm \
      --volume=/dev/dri \
      --env="DISPLAY"  \
      --env="QT_X11_NO_MITSHM=1" \
      --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
      ros:nvidia \
      bash -c "$@"
  rviz:
    usage: ROS visualization tool
    cmd: ahoy ros "roscore & rosrun rviz rviz"
  rqt_bag:
    usage: ROS bag visualizer
    cmd: ahoy ros "roscore & rqt_bag"
      

